var app = angular.module("ModelVoteApp", ["firebase"]);
app.controller("ModelVoteCtrl", function ($scope, $firebaseArray) {
    var ref = new Firebase("https://modeledge.firebaseio.com/Phone%20Apps/ModelVote/IMG_List");
    // create a synchronized array
    $scope.PhotoList = $firebaseArray(ref);
    // add new items to the array
    // the message is automatically added to Firebase!
    $scope.addPhoto = function () {
        $scope.PhotoList.$add({
            text: $scope.newMessageText,
            ALT: "some alt text",
            Caption:"Caption Text",
            Class:"CSS_Class",
            Date: "DT_Stamp",
            Description: "Long Data ",
            ModelName: "Person",
            Title: "Title Vale",
            URL: ".jpg",
            Views: "####"
        });
    };
    // click on `index.html` above to see $remove() and $save() in action

    // Generate a reference to a new location and add some data using push()
    var newPostRef = postsRef.push({
        author: "gracehop",
        title: "Announcing COBOL, a New Programming Language"
    });
    // Get the unique ID generated by push()
    var postID = newPostRef.key();
});